{{- if .Values.statsd.token -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "exceptionless.fullname" . }}-statsd
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-statsd
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ template "exceptionless.fullname" . }}-statsd
  template:
    metadata:
      labels:
        app: {{ template "exceptionless.name" . }}
        component: {{ template "exceptionless.fullname" . }}-statsd
        chart: {{ template "exceptionless.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "exceptionless.name" . }}-statsd
          image: everydayhero/statsd:latest
          imagePullPolicy: {{ .Values.jobs.image.pullPolicy }}
          env:
            - name: LIBRATO_SOURCE
              value: unique-per-statsd-instance
            - name: LIBRATO_TOKEN
              value: {{ .Values.statsd.token }}
            - name: LIBRATO_USER
              value: {{ .Values.statsd.user }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "exceptionless.fullname" . }}-statsd
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-statsd
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8125
      targetPort: 8125
      protocol: UDP
      name: statsd
  selector:
    component: {{ template "exceptionless.fullname" . }}-statsd

{{- end -}}