# helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
# helm install ex-$ENV-slack banzaicloud-stable/slackin --namespace ex-$ENV --values ex-slack-values.yaml --set "slackApiToken=$SLACK_API_TOKEN" --set "googleCaptchaSecret=$CAPTCHA_SECRET" --set "googleCaptchaSiteKey=$CAPTCHA_KEY"

slackinTheme: "light"
slackinPort: 3000
slackSubdomain: "exceptionless"
replicaCount: 1

image:
  repository: banzaicloud/slackin-extended
  tag: 0.13.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-prod
  path: /
  hosts:
    - slack.exceptionless.com
  tls:
    - secretName: ex-prod-slack-tls
      hosts:
        - slack.exceptionless.com