apiVersion:  v1
kind: Pod
metadata:
  name: ex-dev-migration
  namespace: ex-dev
spec:
  restartPolicy: Never
  containers:
    - name: ex-dev-jobs-data-migration
      image: exceptionless/job-ci:6.0.3583-pre
      resources:
        requests:
          memory: 75Mi
          cpu: 200m
        limits:
          memory: 125Mi
          cpu: 400m
      args: [DataMigration]
      env:
        - name: EX_ConnectionStrings__ElasticsearchToMigrate
          value: 'server=http://10.0.0.4:9200;field-limit=2000'
#        - name: EX_ReindexCutOffDate
#          value: '2019-12-02T18:00:00.00Z'
      envFrom:
        - configMapRef:
            name: ex-dev-config
